version:  '3.2'
services:
  userscan-server:
    build:
        dockerfile: Dockerfile
        context: .
    env_file:
    - .env
    network_mode: "host"
    depends_on:
      postgres:
        condition: service_healthy

  postgres-testnet:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-userscan_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: userscan_db
      PGDATA: /data/database
    volumes:
      - pgstore:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    network_mode: "host"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d userscan_db -U userscan_user" ]
      interval: 5s
      timeout: 5s
      retries: 5

   postgres-mainnet:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-userscan_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: userscan_db
      PGDATA: /data/database
    volumes:
      - pgstore:/var/lib/postgresql/data
    ports:
      - '7432:5432'
    network_mode: "host"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d userscan_db -U userscan_user" ]
      interval: 5s
      timeout: 5s
      retries: 5   

  postgres-for-e2e-test:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-userscan_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: userscan_db
      PGDATA: /data/test-database
    volumes:
      - pgstore:/var/lib/postgres-for-e2e-test/data
    ports:
      - '6432:5432'
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes: 
      - redis:/data  
volumes:
  redis:
      driver: local
  pgstore: